name: Linux RDP SSH

on:
  workflow_dispatch:

jobs:
  ssh-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "YOUR_PUBLIC_KEY_HERE" >> ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          echo "✅ SSH key added successfully."

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TS_KEY }} --hostname="linux-runner" --ssh
          echo "Tailscale IP:"
          tailscale ip -4
          echo "You can SSH using: ssh runner@$(tailscale ip -4)"
